#####################################################
## | |__   ___  ___ __ _| |_ ___  _ __ ___ | |__   ##
## | '_ \ / _ \/ __/ _` | __/ _ \| '_ ` _ \| '_ \  ##
## | | | |  __/ (_| (_| | || (_) | | | | | | |_) | ##
## |_| |_|\___|\___\__,_|\__\___/|_| |_| |_|_.__/  ##
#####################################################

# For more information see: https://github.com/shandley/hecatomb and https://hecatomb.readthedocs.io/en/latest/

---


##################
# Run Parameters #
##################

# Database installation location, leave blank = use hecatomb install location
Databases:

### STICK TO YOUR SYSTEM'S CPU:RAM RATIO FOR THESE
BigJobMem: 64000     # Memory for MMSeqs in megabytes (e.g 64GB = 64000, recommend >= 64000)
BigJobCpu: 24        # Threads for MMSeqs (recommend >= 16)
BigJobTimeMin: 1440  # Max runtime in minutes for MMSeqs (this is only enforced by the Snakemake profile)
MediumJobMem: 32000  # Memory for Megahit/Flye in megabytes (recommend >= 32000)
MediumJobCpu: 16     # CPUs for Megahit/Flye in megabytes (recommend >= 16)
SmallJobMem: 16000   # Memory for BBTools etc. in megabytes (recommend >= 16000)
SmallJobCpu: 8       # CPUs for BBTools etc. (recommend >= 8)
                     # default CPUs = 1
# SPECIFY DEFAULT MEM AND TIME IN YOUR PROFILE - see example profile config.yaml
defaultJobs: 100     # Default concurrent jobs (for use with --profile)

# Some jobs need more RAM; go over your CPU:RAM ratio if needed
MoreRamMem: 16000    # Memory for slightly RAM-hungry jobs in megabytes (recommend >= 16000)
MoreRamCpu: 2        # CPUs for slightly RAM-hungry jobs (recommend >= 2)


############################
# Optional Rule Parameters #
############################

# Preprocessing
QSCORE: 15 # Read quality trimming score (rule fastp_preprocessing in 01_preprocessing.smk)
READ_MINLENGTH: 90 # Minimum read length during QC steps (rule fastp_preprocessing in 01_preprocessing.smk)
CONTIG_MINLENGTH: 1000 # Read minimum length (rule contig_reformating_and_stats in 01_preprocessing.smk)
CUTTAIL_WINDOW: 25 # Sliding window size for low qual read filter rule fastp_preprocessing in 01_preprocessing.smk)
DEDUP_ACCURACY: 4 # Specify the level (1 ~ 6). The higher level means more memory usage and more running time, but lower risk of incorrect deduplication marking (rule fastp_preprocessing in 01_preprocessing.smk)
COMPRESSION: 1 # Compression level for gzip output (1 ~ 9). 1 is fastest, 9 is smallest. Default is 1, based on assumption of large scratch space (rule fastp_preprocessing in 01_preprocessing.smk)
ENTROPY: 0.7 # For adding host genomes

# CLUSTER READS TO SEQTABLE (MMSEQS EASY-LINCLUST)
 # -c = req coverage of target seq
 # --min-seq-id = req identity [0-1] of alignment
linclustParams:
 --kmer-per-seq-scale 0.3
 -c 0.8
 --cov-mode 1
 --min-seq-id 0.97
 --alignment-mode 3

# If the following LCA-calculated TaxIDs are encountered, defer to the top hit TaxID
 # 0 = unclassified
 # 1 = root
 # 2 = bacteria root
 # 10239 = virus root
 # 131567 = cell org root
 # 12429 = unclass virus
 # 2759 = eukaryota root
 # 12333 = unclass phage
taxIdIgnore: 0 1 2 10239 131567 12429 2759

###########################################
# Canu settings (for longread assemblies) #
###########################################

# recommended correctedErrorRate is 0.16 to 0.12 (depending on coverage) for nanopore and
# 0.105 to 0.040 (depending on coverage) for pacbio (non-HiFi) - below is low-coverage nanopore
# https://canu.readthedocs.io/en/latest/faq.html#what-parameters-can-i-tweak
canuSettings:
 correctedErrorRate=0.16
 maxInputCoverage=10000
 minInputCoverage=0
 corOutCoverage=10000
 corMhapSensitivity=high
 corMinCoverage=0
 useGrid=False
 stopOnLowCoverage=False
 genomeSize=10M
 -nanopore
# -pacbio
# -pacbio-hifi

###################
# MMSeqs settings #
###################

# ALIGNMENT FILTERING CUTOFFS
  # --min-length for AA should be equal or less than 1/3 of READ_MINLENGTH
  # --min-length for NT should be equal or less than READ_MINLENGTH
filtAAprimary:
 --min-length 30
 -e 1e-3
filtAAsecondary:
 --min-length 30
 -e 1e-5
filtNTprimary:
 --min-length 90
 -e 1e-10
filtNTsecondary:
 --min-length 90
 -e 1e-20

# PERFORMANCE SETTINGS - SEE MMSEQS DOCUMENTATION FOR DETAILS
# sensitive AA search
perfAA:
 --start-sens 1
 --sens-steps 3
 -s 7
 --lca-mode 2
 --shuffle 0
# fast AA search
perfAAfast:
 -s 4.0
 --lca-mode 2
 --shuffle 0
# sensitive NT search
perfNT:
 --start-sens 2
 -s 7
 --sens-steps 3
# fast NT search
perfNTfast:
 -s 4.0
